name: Generate Dist File for Plugin

on:
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
      
permissions:
  contents: write

jobs:
  generate-json-and-release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4.2.2

      - name: Run WP Self-Host Update JSON Generator
        uses: sonderformat-llc/wp-self-host-updater-generator@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
